### ISSUE TITLE
ValueError: Invalid SQL Statement

### ISSUE THREAD

**Issue by d33tah** [allanlw/dhtplay#4]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/d33tah/workspace/dhtplay/lib/sql/thread.py", line 70, in run
    raise ValueError("Invalid SQL Statement - {0} ({1})".format(stmt, e))
ValueError: Invalid SQL Statement - (9, 'SELECT nodes.* FROM nodes INNER JOIN buckets ON\n                            nodes.bucket_id=buckets.id WHERE nodes.contact=?\n                            AND buckets.server_id=? LIMIT 1', (<lib.util.contactinfo.ContactInfo instance at 0x7fe176f4c9e0>, 1)) (Error binding parameter 0 - probably unsupported type.)
```

**Comment by allanlw** [comment]
This looks like an error with the custom type adapter for SQLite for the contactinfo class. Was there something specific that you did that caused this?

**Comment by d33tah** [comment]
@allanlw: nope, just run the server and pinged router.bittorrent.com. I think I walked around this one with this patch:

```
diff --git a/lib/sql/queries.py b/lib/sql/queries.py
index 2252961..79aa7c7 100644
--- a/lib/sql/queries.py
+++ b/lib/sql/queries.py
@@ -34,7 +34,7 @@ def create_node(conn, hash, contact, bucket, good, pending, version, received,
   return conn.insert("""INSERT INTO nodes(id, hash, contact, bucket_id, good,
                         pending, version, received, created, updated, sent)
                         VALUES (NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
-                      (hash, contact, bucket, good, pending, version,
+                      (hash, str(contact), bucket, good, pending, version,
                        received, time, time, sent))
 
 def set_bucket_updated(conn, id, time):
@@ -72,7 +72,7 @@ def get_node_by_contact(conn, server_id, contact):
   return conn.select_one("""SELECT nodes.* FROM nodes INNER JOIN buckets ON
                             nodes.bucket_id=buckets.id WHERE nodes.contact=?
                             AND buckets.server_id=? LIMIT 1""",
-                         (contact, server_id))
+                         (str(contact), server_id))
 
 def set_node_updated(conn, id, time, version, received):
   conn.execute("""UPDATE nodes SET updated=?, version=?, received=received+?
@@ -128,7 +128,7 @@ def get_all_peers(conn):
 
 def get_peer_by_contact(conn, contact):
   return conn.select_one("SELECT * FROM peers WHERE contact=? LIMIT 1",
-                         (contact,))
+                         (str(contact),))
 
 def add_peer(conn, contact, time):
   return conn.insert("INSERT INTO peers VALUES (NULL, ?, ?, ?)",
```

**Comment by allanlw** [comment]
Yeah, that should work, but I'm really not sure why this is an issue.

Actually, are you using python3?

**Comment by d33tah** [comment]
Nope, 2.7.10 on Ubuntu 15.10 on DigitalOcean in FRA1.

**Comment by allanlw** [comment]
It's probably that this line should return a string instead of a buffer: https://github.com/allanlw/dhtplay/blob/master/lib/util/contactinfo.py#L56

I wonder if something changed in one of the point revisions of sqlite that broke using buffers for type adapters.

Also I think your patch doesn't work because ContactInfo(str(ContactInfo("127.0.0.1", 8000))) won't parse correctly.

The patch I would suggest is to change that line (line 56) to just `return result`

**Comment by allanlw** [comment]
Or even better, https://github.com/allanlw/dhtplay/blob/master/lib/util/contactinfo.py#L68 could be `return str(self.get_packed())`

**Comment by d33tah** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/d33tah/workspace/dhtplay/lib/sql/thread.py", line 70, in run
    raise ValueError("Invalid SQL Statement - {0} ({1})".format(stmt, e))
ValueError: Invalid SQL Statement - (9, 'SELECT nodes.* FROM nodes INNER JOIN buckets ON\n                            nodes.bucket_id=buckets.id WHERE nodes.contact=?\n                            AND buckets.server_id=? LIMIT 1', (<lib.util.contactinfo.ContactInfo instance at 0x7f6426d34050>, 1)) (Error binding parameter 0 - probably unsupported type.)
```

I reverted my changes and got the error above after trying:
```diff
diff --git a/lib/util/contactinfo.py b/lib/util/contactinfo.py
index c4de3cf..3c00b2b 100644
--- a/lib/util/contactinfo.py
+++ b/lib/util/contactinfo.py
@@ -53,7 +53,7 @@ class ContactInfo:
     """Returns a BEP_0005 'packed' representation of the addr+port."""
     result = self.get_packed_host()
     result += chr(self.port >> 8) + chr(self.port % 256)
-    return buffer(result)
+    return result
   def get_packed_host(self):
     """Returns a BEP_0005 'packed' representation of the addr."""
     try:
@@ -65,4 +65,4 @@ class ContactInfo:
     return "{0}:{1}".format(self.host, self.port)
   def __conform__(self, protocol):
     if protocol is sqlite3.PrepareProtocol:
-      return self.get_packed()
+      return str(self.get_packed())
```

**Comment by d33tah** [comment]
AFK a couple hours.

**Comment by allanlw** [comment]
Weird. I'll play around with it tonight.

**Comment by allanlw** [comment]
Fixed. At some point objects started needing to be new-style classes for `__conform__` to work properly. I have absolutely no idea when that happened.

Test case:
  - Create server with bind address 0.0.0.0 and public address of my server's IP. Both ports 6881.
  - Select the server on the right.
  - Ping: host router.bittorrent.com, port 6881
  - Select the new host, right click, select Find Node, enter "3876cab4535c1b2a81cdeffda19408928d264c6a" (ubuntu-gnome-14.04.4-desktop-i386.iso) infohash.
  - New nodes show up as a result of the query.

Let me know if you have any other problems. Marking this as closed.

**Comment by allanlw** [comment]
Also, the root of this issue I think is something very weird going on with the way that old style classes interact with the microprotocols code in the sqlite module. 
https://github.com/python/cpython/blob/2.7/Modules/_sqlite/microprotocols.c#L76

I debugged it and the first time a ContactInfo is put in (when the server is created) it adapts fine, but the second time `pysqlite_microprotocols_adapt` returns `NULL`. I couldn't figure out why, but it seems to fail to find the `__conform__` method on the object for some reason. Regardless, using a new style class seems to fix the issue so I'm not going to let it keep me up any later.

**Comment by mazerty** [comment]
it seems the error appeared again
python 2.7 on ubuntu 18.04
almost the same test case :
* create new server
* ping router.bittorrent.com, default port
freezes and this message appears on the console :
ValueError: Invalid SQL Statement - (9, 'SELECT nodes.* FROM nodes INNER JOIN buckets ON\n                            nodes.bucket_id=buckets.id WHERE nodes.contact=?\n                            AND buckets.server_id=? LIMIT 1', (<lib.util.contactinfo.ContactInfo object at 0x7f321808b690>, 1)) (Error binding parameter 0 - probably unsupported type.)
